Attendance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('signinsheet/')),
    url(r'^signinsheet/', include('signinsheet.urls', namespace='signinsheet')),
    url(r'^admin/', admin.site.urls),
]

api/urls.py
from django.conf.urls import url

from . import views

# Rest Interface
urlpatterns = [
    url(r'^classes/$',
        views.ClassList.as_view(),
        name='rest_class'),
    url(r'^students/(?P<class_key>[0-9]+)/$',
        views.StudentList.as_view(),
        name='rest_students'),
    url(r'^sessions/$',
        views.SessionList.as_view(),
        name='rest_session'),
    url(r'^sessions/(?P<class_key>[0-9]+)/$',
        views.SessionList.as_view(),
        name='rest_sessions_class'),
    url(r'^sessions/(?P<pk>[0-9]+)/$',
        views.SessionDetail.as_view(),
        name='rest_session_detail'),
    url(r'^sessions_update/(?P<pk>[0-9]+)/$',
        views.SessionDetail.as_view(),
        name='rest_session_update'),
    url(r'^current_user/$',
        views.CurrentUser.as_view(),
        name='rest_current_user'),
]

attendance/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ClassView.as_view(), name='choose_class'),
    url(r'^signin/$', views.SignInView.as_view(), name='signin'),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^student_detail/(?P<pk>[0-9]+)/(?P<class>[0-9]+)$', views.StudentDetailView.as_view(), name='student_detail'),
]

class_management/urls.py
"""
URL Patterns for root

Included are:
* / -redirects to attendance/
* attendance/ - Currently just attendance sign-in sheet
* admin/ - Site admin page (requires login)
* api-token-path/ - Get auth token (requires proper credential headers)
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

from rest_framework.authtoken import views

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('attendance/')),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^instructor/', include('instructor.urls', namespace='instructor')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token),
]

instructor/urls.py
from django.conf.urls import url
from django.http import HttpResponseRedirect

from . import views

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('instructor/login')),
    url(r'^index/$', views.InstructorIndexView.as_view(), name='instructor_index'),
    url(r'^student_list/$', views.StudentListView.as_view(), name='instructor_student_list'),
    url(r'^create_class/$', views.CreateClassView.as_view(), name='instructor_create_class'),
    url(r'^create_student/$', views.CreateStudentView.as_view(), name='instructor_create_student'),
    url(r'^class_detail/(?P<pk>[0-9]+)$', views.ClassDetailView.as_view(), name='class_detail'),
    url(r'^create_session/(?P<pk>[0-9]+)$', views.create_session, name='instructor_create_session'),
    url(r'^enroll_students/(?P<pk>[0-9]+)$', views.EnrollStudentsView.as_view(), name='enroll_students'),
    url(r'^update_session/(?P<pk>[0-9]+)$', views.update_session, name='update_session'),
    url(r'^close_sessions/(?P<class_id>[0-9]+)$', views.close_sessions, name='close_sessions'),
    url(r'^download/(?P<class_id>[0-9]+)$', views.output_csv, name='csv'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/&', views.user_logout, name='logout'),
]

attendance/models.py
from django.conf import settings
from django.db import models
import datetime

from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Class(models.Model):
    """
    Models a class with a list of students
    """
    SPRING = 0
    FALL = 1

    SEMESTERS = (
        (SPRING, 'Spring'),
        (FALL, 'Fall')
    )

    semester = models.SmallIntegerField(choices=SEMESTERS)
    year = models.IntegerField()
    class_id = models.CharField(max_length=12)
    name = models.CharField(max_length=30)
    enrolled_students = models.ManyToManyField('Student', blank=True)

    class Meta:
        verbose_name_plural = "Classes"

    def __str__(self):
        return self.class_id + ' ' + str((self.SEMESTERS[self.semester])[1]) + ' ' + str(self.year)


class Student(models.Model):
    """
    Each student must sign in as a 'user' sort of each day
    """
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    student_id = models.CharField(max_length=6, unique=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.student_id + ' ' + self.last_name


class Session(models.Model):
    """
    One of these for each day of the term
    """
    date = models.DateField(default=datetime.date.today)
    password = models.CharField(max_length=16)
    session_class = models.ForeignKey(Class)
    students_present = models.ManyToManyField(Student, blank=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return self.date.strftime("%Y-%m-%d")


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    """
    :param sender:
    :param instance:
    :param created:
    :param kwargs:
    :return:
    """
    if created:
        Token.objects.create(user=instance)

attendance/forms.py
from django import forms
from .models import Class


class SignInForm(forms.Form):
    student_id = forms.CharField(label='Student ID', max_length=6)
    today_password = forms.CharField(label="Today's Password", max_length=20, widget=forms.PasswordInput)


class ChooseClassForm(forms.Form):
    classes = forms.ModelChoiceField(label='Class', queryset=Class.objects.all().order_by('name'))

attendance/views.py
import csv
from datetime import date

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormView

from .forms import SignInForm, ChooseClassForm
from .models import Class, Student, Session


class ClassView(FormView):
    template_name = 'attendance/class.html'
    form_class = ChooseClassForm
    success_url = '/attendance/signin/'

    def form_valid(self, form):
        c = form.cleaned_data['classes']
        return HttpResponseRedirect(self.get_success_url() + "?class=" + c.class_id)


class SignInView(FormView):
    template_name = 'attendance/signin.html'
    form_class = SignInForm


class StudentDetailView(generic.DetailView):
    template_name = 'attendance/student_detail.html'
    model = Student
    context_object_name = 'student_detail'

    def get_context_data(self, **kwargs):
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        my_student = self.get_object()
        my_class = Class.objects.get(id=self.kwargs['class'])
        my_sessions = Session.objects.filter(session_class=my_class).order_by('date')
        context['student'] = my_student
        context['class'] = my_class
        context['sessions'] = my_sessions
        return context


def verify(request):
    """
    Verifies student id, class, and password. If it all matches up, the student is marked present for the day.
    :param request:
    :return:
    """
    if request.GET:
        today = date.today()
        try:
            student = Student.objects.get(student_id=request.GET.get('student_id'))
        except Student.DoesNotExist:
            return HttpResponse("Student Does Not Exist")

        current_class = Class.objects.get(class_id=request.GET.get('class_id'))
        class_id = current_class.id
        sessions = Session.objects.filter(session_class=class_id).filter(date__exact=today)
        s = sessions[0]

        if s.students_present.filter(id=student.id).exists():
            return HttpResponseRedirect('../../attendance/student_detail/%i/%i' % (student.id, class_id))
        elif not s.is_open:
            return HttpResponse("This session is closed for signin.")
        elif student in current_class.enrolled_students.all() and request.GET.get('today_password') == s.password:
            s.students_present.add(student)
            s.save()
            return HttpResponseRedirect('../../attendance/student_detail/%i/%i' % (student.id, class_id))
        else:
            return HttpResponse("<h3>Password or Class incorrect</h3>")

attendance/templates/attendance/class.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Your Class</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "attendance/stylesheets/main.css" %}" type="text/css" />

</head>
<body>
<div class="container">
    <div class="page-header">
        <div class="row row-table">
            <div class="vcenter">
                <div class="col-lg-2 col-sm-6"><img class="img-responsive" src="{% static "attendance/images/stem_logo.jpg" %}"/></div>
                <div class="col-lg-10 col-sm-6"><h1>Class management</h1></div>
            </div>
        </div>
    </div>
    <strong>{% now "SHORT_DATE_FORMAT" %}</strong>

    <form action="{% url 'attendance:choose_class' %}" method="post">
        {%  csrf_token %}
        <legend>Choose your class</legend>
        <div class="form-group">
            {% for field in form %}
                <label class="control-label" for="{{ field.name }}">{{ field.label }}</label>
                {{ field|attr:"class:form-control" }}
            {% endfor %}
        </div>
        <input type="submit" value="Submit" class="btn btn-primary" />
    </form>

</div>

<div class="container">
    <footer class="panel-footer">
        <a href="{% url 'instructor:login' %}"><button class="btn btn-primary">Instructor</button></a>
    </footer>
</div>

<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

attendance/templates/attendance/signin.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "attendance/stylesheets/main.css" %}" type="text/css" />

</head>
<body>

<div class="container">
    <div class="page-header">
        <div class="row row-table">
            <div class="vcenter">
                <div class="col-lg-2 col-md-3 col-sm-6"><img class="img-responsive" src="{% static "attendance/images/stem_logo.jpg" %}"/></div>
                <div class="col-lg-10 col-md-9 col-sm-6"><h1>{{ request.GET.class }}</h1></div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-lg-4 col-md-3"></div>
    <div class="col-lg-4 col-md-6 col-sm-12">
        <strong>{% now "SHORT_DATE_FORMAT" %}</strong>

        <form action="{% url 'attendance:verify' %}?class={{ request.GET.class }}" method="get">
            {%  csrf_token %}
            <div class="form-group">
                <label class="control-label" for="class_id">Class</label>
                <input type="text" class="form-control" name="class_id" id="class_id" required readonly value="{{ request.GET.class }}"/>
                {% for field in form %}
                    <label class="control-label" for="{{ field.name }}">{{ field.label }}</label>
                    {{ field|attr:"class:form-control" }}
                {% endfor %}
            </div>
            <input type="submit" value="Submit" class="btn btn-primary" />
        </form>
    </div>
    <div class="col-lg-4 col-md-3"></div>
    </div>
</div>

<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

attendance/templates/attendance/student_detail.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Data</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "attendance/stylesheets/main.css" %}" type="text/css" />

    <div class="container">

        <div class="page-header">
            <div class="row row-table">
                <div class="vcenter">
                    <div class="col-lg-2 col-sm-6"><img class="img-responsive" src="{% static "instructor/images/stem_logo.jpg" %}"/></div>
                    <div class="col-lg-10 col-sm-6"><h1>Class management</h1></div>
                </div>
            </div>
        </div>

        <section>
            <div class="well">
                {% if student_detail %}
                    <h3>Today: {% now "SHORT_DATE_FORMAT" %}</h3>

                    <table class="table table-bordered table-condensed table-hover">
                        <legend>{{ student.last_name }}, {{ student.first_name }} - {{ class.class_id }}</legend>
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Attendance</th>
                        </tr>
                        </thead>
                        {% for session in sessions %}
                            <tr>
                                <th>{{ session.date }}</th>
                                {% if student in session.students_present.all %}
                                    <td>P</td>
                                {% else %}
                                    <td>A</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>


                {% endif %}

            </div>
        </section>

    </div>
</head>
<body>



<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>