Attendance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('signinsheet/')),
    url(r'^signinsheet/', include('signinsheet.urls', namespace='signinsheet')),
    url(r'^admin/', admin.site.urls),
]

api/urls.py
from django.conf.urls import url

from . import views

# Rest Interface
urlpatterns = [
    url(r'^classes/$',
        views.ClassList.as_view(),
        name='rest_class'),
    url(r'^students/(?P<class_key>[0-9]+)/$',
        views.StudentList.as_view(),
        name='rest_students'),
    url(r'^sessions/$',
        views.SessionList.as_view(),
        name='rest_session'),
    url(r'^sessions/(?P<class_key>[0-9]+)/$',
        views.SessionList.as_view(),
        name='rest_sessions_class'),
    url(r'^sessions/(?P<pk>[0-9]+)/$',
        views.SessionDetail.as_view(),
        name='rest_session_detail'),
    url(r'^sessions_update/(?P<pk>[0-9]+)/$',
        views.SessionDetail.as_view(),
        name='rest_session_update'),
    url(r'^current_user/$',
        views.CurrentUser.as_view(),
        name='rest_current_user'),
]

class_management/urls.py
"""
URL Patterns for root

Included are:
* / -redirects to attendance/
* attendance/ - Currently just attendance sign-in sheet
* admin/ - Site admin page (requires login)
* api-token-path/ - Get auth token (requires proper credential headers)
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

from rest_framework.authtoken import views

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('attendance/')),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^instructor/', include('instructor.urls', namespace='instructor')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token),
]

instructor/urls.py
from django.conf.urls import url
from django.http import HttpResponseRedirect

from . import views

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('instructor/login')),
    url(r'^index/$', views.InstructorIndexView.as_view(), name='instructor_index'),
    url(r'^student_list/$', views.StudentListView.as_view(), name='instructor_student_list'),
    url(r'^create_class/$', views.CreateClassView.as_view(), name='instructor_create_class'),
    url(r'^create_student/$', views.CreateStudentView.as_view(), name='instructor_create_student'),
    url(r'^class_detail/(?P<pk>[0-9]+)$', views.ClassDetailView.as_view(), name='class_detail'),
    url(r'^create_session/(?P<pk>[0-9]+)$', views.create_session, name='instructor_create_session'),
    url(r'^enroll_students/(?P<pk>[0-9]+)$', views.EnrollStudentsView.as_view(), name='enroll_students'),
    url(r'^update_session/(?P<pk>[0-9]+)$', views.update_session, name='update_session'),
    url(r'^close_sessions/(?P<class_id>[0-9]+)$', views.close_sessions, name='close_sessions'),
    url(r'^download/(?P<class_id>[0-9]+)$', views.output_csv, name='csv'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/&', views.user_logout, name='logout'),
]

attendance/models.py
from django.conf import settings
from django.db import models
import datetime

from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Class(models.Model):
    """
    Models a class with a list of students
    """
    SPRING = 0
    FALL = 1

    SEMESTERS = (
        (SPRING, 'Spring'),
        (FALL, 'Fall')
    )

    semester = models.SmallIntegerField(choices=SEMESTERS)
    year = models.IntegerField()
    class_id = models.CharField(max_length=12)
    name = models.CharField(max_length=30)
    enrolled_students = models.ManyToManyField('Student', blank=True)

    class Meta:
        verbose_name_plural = "Classes"

    def __str__(self):
        return self.class_id + ' ' + str((self.SEMESTERS[self.semester])[1]) + ' ' + str(self.year)


class Student(models.Model):
    """
    Each student must sign in as a 'user' sort of each day
    """
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    student_id = models.CharField(max_length=6, unique=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.student_id + ' ' + self.last_name


class Session(models.Model):
    """
    One of these for each day of the term
    """
    date = models.DateField(default=datetime.date.today)
    password = models.CharField(max_length=16)
    session_class = models.ForeignKey(Class)
    students_present = models.ManyToManyField(Student, blank=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return self.date.strftime("%Y-%m-%d")


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    """
    :param sender:
    :param instance:
    :param created:
    :param kwargs:
    :return:
    """
    if created:
        Token.objects.create(user=instance)

instructor/models.py
from django.db import models

# Create your models here.

instructor/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

from attendance.models import Class, Student, Session


class CreateClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['semester', 'year', 'class_id', 'name']


class EnrollStudentsForm(forms.ModelForm):
    class Meta:
        model = Class
        exclude = ['semester', 'year', 'class_id', 'name']

    def __init__(self, *args, **kwargs):
        super(EnrollStudentsForm, self).__init__(*args, **kwargs)
        self.fields["enrolled_students"].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields["enrolled_students"].help_text = ""
        self.fields["enrolled_students"].queryset = Student.objects.all()


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'student_id']


class CreateSessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = ['date', 'session_class', 'password']
        widgets = {
            'date': AdminDateWidget(attrs={'class': 'datepicker', }),
        }


class UpdateSessionForm(forms.ModelForm):
    class Meta:
        model = Session
        exclude = ['date', 'password', 'is_open', 'session_class']

    def __init__(self, session, *args, **kwargs):
        super(UpdateSessionForm, self).__init__(*args, **kwargs)
        c = session.session_class
        ids = session.students_present.values_list('id', flat=True)
        self.fields['students_present'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['students_present'].helpt_text = "Who was present?"
        self.fields['students_present'].queryset = c.enrolled_students.all()
        self.fields['students_present'].initial = ids

instructor/views.py
import csv

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from attendance.models import Class, Session, Student
from .forms import CreateClassForm, CreateStudentForm, EnrollStudentsForm, CreateSessionForm, UpdateSessionForm


class InstructorIndexView(generic.ListView):
    template_name = "instructor/index.html"
    context_object_name = "class_list"

    def get_queryset(self):
        classes = None
        if self.request.user.is_authenticated():
            classes = Class.objects.all()
        return classes


class StudentListView(generic.ListView):
    template_name = "instructor/student_list.html"
    context_object_name = 'students'

    def get_queryset(self):
        students = None
        if self.request.user.is_authenticated():
            students = Student.objects.all().order_by('last_name')
        return students

    def get_context_data(self, **kwargs):
        context = super(StudentListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            my_classes = Class.objects.all()
            context['classes'] = my_classes
        return context


class CreateClassView(generic.CreateView):
    template_name = "instructor/create_class.html"
    form_class = CreateClassForm
    success_url = '/instructor/index/'

    def form_invalid(self, form):
        return HttpResponse("Form is invalid...redo it.")


@login_required
def create_session(request, pk):
    if request.method == 'POST':
        form = CreateSessionForm(request.POST)
        if form.is_valid():
            s = form.save()
            return HttpResponseRedirect('/instructor/class_detail/%i' % s.session_class.id)
    else:
        obj = Class.objects.get(id=pk)
        form = CreateSessionForm(initial={'session_class': obj.id})
        return render(request, "instructor/create_session.html", {"form": form})


class EnrollStudentsView(generic.UpdateView):
    template_name = 'instructor/enroll_students.html'
    form_class = EnrollStudentsForm
    success_url = '/instructor/index'

    def get_object(self, queryset=None):
        obj = Class.objects.get(id=self.kwargs['pk'])
        return obj


def update_session(request, pk):
    if request.method == 'POST':
        s = Session.objects.get(id=pk)
        c = s.session_class
        if 'students_present' in request.POST:
            s.students_present.clear()
            spid = request.POST.getlist('students_present')
            spid = list(map(int, spid))
            sp = Student.objects.filter(id__in=spid)
            for student in sp:
                s.students_present.add(student)
        else:
            s.students_present.clear()
        return HttpResponseRedirect('/instructor/class_detail/%i' % c.id)
    else:
        s = Session.objects.get(id=pk)
        form = UpdateSessionForm(s)
        ctx = {"form": form, "session": s}
        return render(request, "instructor/update_session.html", ctx)


class CreateStudentView(generic.CreateView):
    template_name = "instructor/create_student.html"
    form_class = CreateStudentForm
    success_url = '/instructor/create_student'

    def form_invalid(self, form):
        return HttpResponse("Form is invalid")


class ClassDetailView(generic.DetailView):
    template_name = "instructor/class_detail.html"
    model = Class
    context_object_name = 'class_detail'

    def get_context_data(self, **kwargs):
        context = super(ClassDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            my_class = self.get_object()
            my_sessions = Session.objects.filter(session_class=my_class).order_by('date')
            context['sessions'] = my_sessions
        return context


def output_csv(request, class_id):
    """
    Outputs selected class to csv file
    :param class_id: id number of class
    :param request: request object
    :return: a csv file attached to http response
    """
    my_class = Class.objects.get(id=class_id)
    disp = 'attachment; filename="attendance_data_' + my_class.class_id + '.csv"'
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = disp

    my_sessions = Session.objects.filter(session_class=my_class).order_by('date')
    my_students = my_class.enrolled_students.order_by('last_name', 'first_name')

    writer = csv.writer(response)
    title_row = [my_class.class_id + " " + my_class.name]
    writer.writerow(title_row)
    header_row = ["Name"]
    for session in my_sessions:
        header_row.append(session.date)
    writer.writerow(header_row)

    for student in my_students:
        data_row = [student.last_name + ", " + student.first_name]
        for session in my_sessions:
            if student.session_set.filter(id=session.id).exists():
                data_row.append("P")
            else:
                data_row.append("A")
        writer.writerow(data_row)

    return response


def close_sessions(request, class_id):
    """
    Closes all open sessions
    :param request:
    :return: HttpResponseRedirect
    """
    if not request.user.is_authenticated:
        HttpResponse("You are not allowed to do that")
    my_class = Class.objects.get(id=class_id)
    my_sessions = Session.objects.filter(session_class=my_class)
    for session in my_sessions:
        session.is_open = False
        session.save()
    return HttpResponseRedirect('/instructor/class_detail/%i' % my_class.id)


def user_login(request):
    """
    Login request view
    :param request:
    :return:
    """
    if request.user.is_authenticated():
        return HttpResponseRedirect('/instructor/index')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/instructor/index/')
            else:
                return HttpResponse('Your account is disabled')
        else:
            print('Invalid Login')
            return HttpResponse('Invalid login details')
    else:
        return render(request, 'instructor/login.html')


@login_required
def user_logout(request):
    """
    Logs current client out
    :param request:
    :return:
    """
    logout(request)
    return HttpResponseRedirect('/attendance/')

instructor/templates/instructor/class_detail.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Data</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "instructor/stylesheets/main.css" %}" type="text/css" />

    <div class="container">

        <div class="page-header">
            <div class="row row-table">
                <div class="vcenter">
                    <div class="col-lg-2 col-sm-6"><img class="img-responsive" src="{% static "instructor/images/stem_logo.jpg" %}"/></div>
                    <div class="col-lg-10 col-sm-6"><h1>Class management</h1></div>
                </div>
            </div>
        </div>

        {% if user.is_authenticated %}
            <section>
                <div class="well">
                    {% if class_detail %}
                        <h3>Today: {% now "SHORT_DATE_FORMAT" %}</h3>

                        <table class="table table-bordered table-condensed table-hover">
                            <legend>{{ class_detail.class_id }} {{ class_detail.name }}</legend>
                            <thead>
                            <tr>
                                <td>Student</td>
                                {% for session in sessions %}
                                    {% if session.is_open %}
                                        <td style="background-color: gold"><a href="{% url 'instructor:update_session' session.id %}">{{ session.date }}</a></td>
                                    {% else %}
                                        <td><a href="{% url 'instructor:update_session' session.id %}">{{ session.date }}</a></td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                            </thead>
                            {% for student in class_detail.enrolled_students.all %}

                                <tr>
                                    <td>{{ student.last_name }}, {{ student.first_name }}</td>
                                    {% for session in sessions %}
                                        {% if student in session.students_present.all %}
                                            <td>P</td>
                                        {% else %}
                                            <td>A</td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>

                            {% endfor %}

                        </table>


                    {% endif %}

                </div>
            </section>
            <section>
                <a href="{% url 'instructor:instructor_index' %}" class="btn btn-primary">
                    <span class="glyphicon glyphicon-home"></span> Index
                </a>
                <a href="{% url 'instructor:instructor_create_session' class_detail.id %}" class="btn btn-primary">
                    <span class="glyphicon glyphicon-bell"></span> Add Session
                </a>
                <a href="{% url 'instructor:close_sessions' class_detail.id %}" class="btn btn-primary">
                    <span class="glyphicon glyphicon-remove"></span> Close Sessions
                </a>
                <a href="{% url 'instructor:enroll_students' class_detail.id %}" class="btn btn-primary">
                    <span class="glyphicon glyphicon-registration-mark"></span> Enroll students
                </a>
                <a href="{% url 'instructor:csv' class_detail.id %}" class="btn btn-primary">
                    <span class="glyphicon glyphicon-download-alt"></span> Download CSV
                </a>
            </section>
        {% endif %}

    </div>
</head>
<body>



<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

instructor/templates/instructor/create_session.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a Session</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

    <link rel="stylesheet" href="{% static "instructor/stylesheets/main.css" %}" type="text/css" />

</head>
<body>



<div class="container">
    <div class="page-header">
        <div class="row row-table">
            <div class="vcenter">
                <div class="col-lg-2 col-sm-6"><img class="img-responsive" src="{% static "instructor/images/stem_logo.jpg" %}"/></div>
                <div class="col-lg-10 col-sm-6"><h1>Class management</h1></div>
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
        <section class="well">
            <form action="" method="post">
                {% csrf_token %}
                <legend>Create a new Session</legend>
                <table>
                    {{ form }}
                </table>
                <input type="submit" value="Submit" />
            </form>
        </section>
    {% endif %}
</div>

<div class="container">
    <footer class="panel-footer">
        {% if user.is_authenticated %}
            <a href="{% url 'instructor:instructor_index' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-step-backward"></span> Back to Index</button></a>
            <a href="{% url 'instructor:instructor_student_list' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-education"></span> Student List</button></a>
        {% endif %}
    </footer>
</div>

<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $('.datepicker').datepicker();
    });
</script>

</body>
</html>

instructor/templates/instructor/index.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instructor Index</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "instructor/stylesheets/main.css" %}" type="text/css" />

</head>
<body>

<div class="container">

    <div class="page-header">
        <div class="row row-table">
            <div class="vcenter">
                <div class="col-lg-2 col-sm-6"><img class="img-responsive" src="{% static "instructor/images/stem_logo.jpg" %}"/></div>
                <div class="col-lg-10 col-sm-6"><h1>Class management</h1></div>
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
        <section class="well">
            <h3>Today: {% now "SHORT_DATE_FORMAT" %}</h3>
            <table class="table, table-responsive table-bordered" width="100%">
                <legend>Select a Class</legend>
                <thead>
                <tr>
                    <th>Class Name</th>
                </tr>
                </thead>
                {% for class in class_list %}
                    <tr>
                        <td><a href="{% url 'instructor:class_detail' class.id %}">{{ class.class_id }}</a></td>
                        <td>{{ class.name }}</td>
                    </tr>
                {% endfor %}
            </table>

        </section>
        <section>
            <div class="btn-group" role="group" aria-label="...">
                <a href="{% url 'instructor:instructor_student_list' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-education"></span> Student List</button></a>
                <a href="{% url 'instructor:instructor_create_student' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Students</button></a>
                <a href="{% url 'instructor:instructor_create_class' %}"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Create Class</button></a>
            </div>
        </section>
    {% endif %}
</div>

<div class="container">
    <footer class="panel-footer">
        {% if user.is_authenticated %}
            <a href="{% url 'instructor:logout' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-log-out"></span> Logout</button></a>
        {% else %}
            <a href="{% url 'instructor:login' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-log-in"></span> Login</button></a>
        {% endif %}
    </footer>
</div>

<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

instructor/templates/instructor/student_list.html
<!DOCTYPE html>
<html lang="en">
{% load static i18n widget_tweaks %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instructor Index</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "instructor/stylesheets/main.css" %}" type="text/css" />

</head>
<body>

<div class="container">
    <div class="page-header">
        <div class="row row-table">
            <div class="vcenter">
                <div class="col-lg-2 col-sm-6"><img class="img-responsive" src="{% static "instructor/images/stem_logo.jpg" %}"/></div>
                <div class="col-lg-10 col-sm-6"><h1>Class management</h1></div>
            </div>
        </div>
    </div>
    {% if user.is_authenticated %}
        <section class="well">
            <h3>Today: {% now "SHORT_DATE_FORMAT" %}</h3>
            <table class="table, table-responsive table-bordered" width="100%">
                <legend>Students</legend>
                <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Student ID</th>
                    <th>Enrolled Classes</th>
                </tr>
                </thead>
                {% for student in students %}
                    <tr>
                        <td>{{ student.last_name }}, {{ student.first_name }}</td>
                        <td>{{ student.student_id }}</td>
                        <td>
                            {% for class in classes %}
                                {% if student in class.enrolled_students.all %}
                                    {{ class.class_id }}&nbsp;
                                {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </table>

        </section>
        <section>
            <a href="{% url 'instructor:instructor_index' %}">
                <button class="btn btn-primary">
                    <span class="glyphicon glyphicon-home"></span> Index
                </button>
            </a>
            <div class="btn-group" role="group">
                <a href="{% url 'instructor:instructor_create_student' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Students</button></a>
            </div>
        </section>
    {% endif %}
</div>
<div class="container">
    <footer class="panel-footer">

        {% if user.is_authenticated %}
            <a href="{% url 'instructor:logout' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-log-out"></span> Logout</button></a>
        {% else %}
            <a href="{% url 'instructor:login' %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-log-in"></span> Login</button></a>
        {% endif %}

    </footer>
</div>


<!-- JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>